//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optimisation_Windows_Capet.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Optimisation_Windows_Capet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _800400p6686EDNmainarrow_outline_red_up {
            get {
                object obj = ResourceManager.GetObject("800400p6686EDNmainarrow_outline_red_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clavier_lumineux_asus {
            get {
                object obj = ResourceManager.GetObject("Clavier lumineux asus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DDU {
            get {
                object obj = ResourceManager.GetObject("DDU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DisableWinTracking {
            get {
                object obj = ResourceManager.GetObject("DisableWinTracking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Display_Driver_Uninstaller {
            get {
                object obj = ResourceManager.GetObject("Display_Driver_Uninstaller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;startup&gt;
        ///      &lt;supportedRuntime version=&quot;v4.0&quot;/&gt;
        ///      &lt;supportedRuntime version=&quot;v2.0.50727&quot;/&gt;
        ///    &lt;/startup&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string Display_Driver_Uninstallerconfig {
            get {
                return ResourceManager.GetString("Display_Driver_Uninstallerconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Display_Driver_Uninstallerpdb {
            get {
                object obj = ResourceManager.GetObject("Display_Driver_Uninstallerpdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy {
            get {
                object obj = ResourceManager.GetObject("giphy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hqdefault {
            get {
                object obj = ResourceManager.GetObject("hqdefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] HtmlAgilityPack {
            get {
                object obj = ResourceManager.GetObject("HtmlAgilityPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] HWMonitor_x64 {
            get {
                object obj = ResourceManager.GetObject("HWMonitor_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] NVIDIAINSPECTOR {
            get {
                object obj = ResourceManager.GetObject("NVIDIAINSPECTOR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] packages {
            get {
                object obj = ResourceManager.GetObject("packages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo {
            get {
                object obj = ResourceManager.GetObject("photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo__1_ {
            get {
                object obj = ResourceManager.GetObject("photo (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Revert {
            get {
                object obj = ResourceManager.GetObject("Revert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_4 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] services {
            get {
                object obj = ResourceManager.GetObject("services", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DisplayDriverUninstaller Version=&quot;17.0.9.1&quot;&gt;
        ///	&lt;Settings&gt;
        ///		&lt;SelectedLanguage&gt;en-US&lt;/SelectedLanguage&gt;
        ///		&lt;RemoveMonitors&gt;True&lt;/RemoveMonitors&gt;
        ///		&lt;RemoveCrimsonCache&gt;True&lt;/RemoveCrimsonCache&gt;
        ///		&lt;RemoveAMDDirs&gt;False&lt;/RemoveAMDDirs&gt;
        ///		&lt;RemoveAMDAudioBus&gt;True&lt;/RemoveAMDAudioBus&gt;
        ///		&lt;RemoveAMDKMPFD&gt;True&lt;/RemoveAMDKMPFD&gt;
        ///		&lt;RemoveNvidiaDirs&gt;False&lt;/RemoveNvidiaDirs&gt;
        ///		&lt;RemovePhysX&gt;True&lt;/RemovePhysX&gt;
        ///		&lt;Remove3DTVPlay&gt;True&lt;/Remove3DTVPlay&gt;
        ///		&lt;RemoveGFE&gt;True&lt;/RemoveG [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SettingsEN {
            get {
                return ResourceManager.GetString("SettingsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DisplayDriverUninstaller Version=&quot;17.0.9.1&quot;&gt;
        ///	&lt;Settings&gt;
        ///		&lt;SelectedLanguage&gt;fr-FR&lt;/SelectedLanguage&gt;
        ///		&lt;RemoveMonitors&gt;True&lt;/RemoveMonitors&gt;
        ///		&lt;RemoveCrimsonCache&gt;True&lt;/RemoveCrimsonCache&gt;
        ///		&lt;RemoveAMDDirs&gt;False&lt;/RemoveAMDDirs&gt;
        ///		&lt;RemoveAMDAudioBus&gt;True&lt;/RemoveAMDAudioBus&gt;
        ///		&lt;RemoveAMDKMPFD&gt;True&lt;/RemoveAMDKMPFD&gt;
        ///		&lt;RemoveNvidiaDirs&gt;False&lt;/RemoveNvidiaDirs&gt;
        ///		&lt;RemovePhysX&gt;True&lt;/RemovePhysX&gt;
        ///		&lt;Remove3DTVPlay&gt;True&lt;/Remove3DTVPlay&gt;
        ///		&lt;RemoveGFE&gt;True&lt;/RemoveG [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SettingsFR {
            get {
                return ResourceManager.GetString("SettingsFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SteamSetup {
            get {
                object obj = ResourceManager.GetObject("SteamSetup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ThrottleStop {
            get {
                object obj = ResourceManager.GetObject("ThrottleStop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] TinyNvidiaUpdateChecker {
            get {
                object obj = ResourceManager.GetObject("TinyNvidiaUpdateChecker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Desktop]
        ///&quot;UserPreferencesMask&quot;=hex:90,12,03,80,12,00,00,00
        ///
        ///.
        /// </summary>
        internal static string UserPreferencesMask {
            get {
                return ResourceManager.GetString("UserPreferencesMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] WinRing0x64DLL {
            get {
                object obj = ResourceManager.GetObject("WinRing0x64DLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] WinRing0x64Sys {
            get {
                object obj = ResourceManager.GetObject("WinRing0x64Sys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] WinRingDLL {
            get {
                object obj = ResourceManager.GetObject("WinRingDLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] WinRingSys {
            get {
                object obj = ResourceManager.GetObject("WinRingSys", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
